package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/dominionthedev/termbox/internal/registry"
	"github.com/spf13/cobra"
)

var setupWizard bool

var setupCmd = &cobra.Command{
	Use:   "setup",
	Short: "Configure termbox and print shell integration instructions",
	Long: `Run with --wizard to configure termbox.env interactively.
Without --wizard, just prints the two lines to add to ~/.zshrc.

Termbox never touches your dotfiles — it prints instructions and you add them.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		if setupWizard {
			return runWizard()
		}
		return printInstructions()
	},
}

func runWizard() error {
	r := bufio.NewReader(os.Stdin)

	fmt.Println()
	fmt.Println("  ╭──────────────────────────────────────╮")
	fmt.Println("  │   Termbox Setup Wizard               │")
	fmt.Println("  ╰──────────────────────────────────────╯")
	fmt.Println()

	home := os.Getenv("HOME")

	defaultTBHome := filepath.Join(home, "Developer", "termbox")
	if existing := os.Getenv("TERMBOX_HOME"); existing != "" {
		defaultTBHome = existing
	}
	tbHome := prompt(r, fmt.Sprintf("Termbox home [%s]", defaultTBHome), defaultTBHome)

	defaultDev := filepath.Join(home, "Developer")
	devFolder := prompt(r, fmt.Sprintf("Developer folder [%s]", defaultDev), defaultDev)

	defaultNotes := filepath.Join(home, "Developer", "notes")
	notesFolder := prompt(r, fmt.Sprintf("Notes folder [%s]", defaultNotes), defaultNotes)

	defaultBanner := filepath.Join(tbHome, "assets", "dominiondev.banner")
	bannerFile := prompt(r, fmt.Sprintf("Banner file [%s]", defaultBanner), defaultBanner)

	showBanner := promptBool(r, "Show banner on shell start? [Y/n]", true)
	defaultTheme := "catppuccin_mocha"
	shellTheme := prompt(r, fmt.Sprintf("Default theme [%s]", defaultTheme), defaultTheme)
	defaultNvim := "default"
	nvimConfig := prompt(r, fmt.Sprintf("Default nvim config [%s]", defaultNvim), defaultNvim)
	defaultPowerup := "core"
	powerup := prompt(r, fmt.Sprintf("Default powerup [%s]", defaultPowerup), defaultPowerup)

	fmt.Println()
	fmt.Println("  Summary:")
	fmt.Printf("  TERMBOX_HOME     = %s\n", tbHome)
	fmt.Printf("  DEV_FOLDER       = %s\n", devFolder)
	fmt.Printf("  NOTE_FOLDER      = %s\n", notesFolder)
	fmt.Printf("  BANNER           = %s\n", bannerFile)
	fmt.Printf("  TERMBOX_SHOW_BANNER = %v\n", showBanner)
	fmt.Printf("  SHELL_THEME      = %s\n", shellTheme)
	fmt.Printf("  TERMBOX_DEFAULT_NVIM = %s\n", nvimConfig)
	fmt.Printf("  TERMBOX_POWERUP  = %s\n", powerup)
	fmt.Println()

	if !promptBool(r, "Write termbox.env? [Y/n]", true) {
		fmt.Println("  Aborted.")
		return nil
	}

	// Create dirs
	for _, dir := range []string{tbHome, devFolder, notesFolder} {
		if err := os.MkdirAll(dir, 0755); err != nil {
			fmt.Fprintf(os.Stderr, "  ⚠  could not create %q: %v\n", dir, err)
		}
	}

	cfgDir := filepath.Join(tbHome, "config")
	if err := os.MkdirAll(cfgDir, 0755); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}

	showBannerStr := "false"
	if showBanner {
		showBannerStr = "true"
	}

	content := fmt.Sprintf(`# termbox.env — Termbox runtime configuration
# Generated by: termbox setup --wizard
#
# SOURCE THIS FIRST in your ~/.zshrc, before sourcing termbox zshrc:
#
#   # ---- termbox env ----
#   source %s/config/termbox.env
#   # ---- termbox zsh ----
#   source $TERMBOX_HOME/config/shell/zshrc

export TERMBOX_HOME="%s"
export TERMBOX_DEV_FOLDER="%s"
export NOTE_FOLDER="%s"
export BANNER="%s"
export TERMBOX_SHOW_BANNER="%s"
export SHELL_THEME="%s"
export TERMBOX_DEFAULT_NVIM="%s"
export TERMBOX_POWERUP="%s"
`, tbHome, tbHome, devFolder, notesFolder, bannerFile, showBannerStr, shellTheme, nvimConfig, powerup)

	envPath := filepath.Join(cfgDir, "termbox.env")
	if err := os.WriteFile(envPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing termbox.env: %w", err)
	}

	fmt.Printf("\n  ✓ Written: %s\n", envPath)
	return printInstructions()
}

func printInstructions() error {
	tbHome := os.Getenv("TERMBOX_HOME")
	if tbHome == "" {
		tbHome = "$HOME/Developer/termbox"
	}
	fmt.Println()
	fmt.Println("  ╭────────────────────────────────────────────────────╮")
	fmt.Println("  │  Add these two lines to the TOP of ~/.zshrc        │")
	fmt.Println("  │  (before any other config)                         │")
	fmt.Println("  ╰────────────────────────────────────────────────────╯")
	fmt.Println()
	fmt.Printf("  # ---- termbox env ----\n")
	fmt.Printf("  source %s/config/termbox.env\n", tbHome)
	fmt.Printf("  # ---- termbox zsh ----\n")
	fmt.Printf("  source $TERMBOX_HOME/config/shell/zshrc\n")
	fmt.Println()
	fmt.Println("  That's it. Termbox is a guest — your shell stays yours.")
	fmt.Println()
	return nil
}

func prompt(r *bufio.Reader, question, defaultVal string) string {
	fmt.Printf("  %s: ", question)
	line, _ := r.ReadString('\n')
	line = strings.TrimSpace(line)
	if line == "" {
		return defaultVal
	}
	return line
}

func promptBool(r *bufio.Reader, question string, defaultVal bool) bool {
	fmt.Printf("  %s: ", question)
	line, _ := r.ReadString('\n')
	switch strings.ToLower(strings.TrimSpace(line)) {
	case "y", "yes":
		return true
	case "n", "no":
		return false
	}
	return defaultVal
}

// expandHome is shared across commands
func expandHome(path string) string {
	return registry.ExpandHome(path)
}

func init() {
	setupCmd.Flags().BoolVarP(&setupWizard, "wizard", "w", false, "Interactive first-time setup")
	rootCmd.AddCommand(setupCmd)
}
