lastupdatecheck: 0
recentrepos:
- /Users/appleplay/Developer/projects/Altschool_projects/todo-app
- /Users/appleplay/Developer/projects/go_projects/wondertone
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
